import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-expect-error: side-effect CSS import without type declarations
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					themes={[
						"light",
						"dark",
						"rose",
						"roseDark",
						"stone",
						"stoneDark",
						"violet",
						"violetDark",
						"yellow",
						"yellowDark",
						"green",
						"greenDark",
					]}
					enableSystem
					disableTransitionOnChange
				>
					<Toaster position="top-right" richColors />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
